version: '2'

services:
    db:
        image: mysql
        volumes:
            - "./data/db:/var/lib/mysql"
        ports:
            - "${EXTERNAL_DB_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build: php7-fpm
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
        environment:
            XDEBUG_CONFIG: remote_host=${HOST_IP_ADDRESS}
    nginx:
        build: nginx
        ports:
            - "${EXTERNAL_WEBSERVER_PORT}:80"
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - "${EXTERNAL_ELK_PORT}:80"
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
